---
title       : ECON 6931 - R Programming
subtitle    : Week 3
author      : James Lamb
job         : Data Scientist | Uptake
logo        : 
framework   : io2012  # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap]            # {mathjax, quiz}
mode        : selfcontained # {selfcontained, standalone, draft}
lib_cdn     : "https://cdn.rawgit.com/ramnathv/slidifyLibraries/master/inst/libraries"
knit        : slidify::knit2slides
--- .toc_slide &twocol

<script src="assets/js/footer_bubbles.js"></script>

<footer>
  <hr></hr>
  <span style="float:right">ECON 6931 - R Programming</span>
</footer>

<h2>Contents</h2>

*** =left

<b class="toc_header"> I. Getting Data from Databases </b>
<ol class="toc" type="none">
    <li> Connecting to the DB <span style="float:right"> 5 </span></li>
    <li> Exploring Without Querying  <span style="float:right"> 5 </span></li>
    <li> Executing Queries <span style="float:right"> 5 </span></li>
</ol>

<b class="toc_header"> II. Working with Web APIs </b>
<ol class = "toc" type="none">
    <li> Application Programming Interfaces<span style="float:right"> 9  </span></li>
    <li> REST API Definition<span style="float:right"> 9  </span></li>
    <li> Authentication with API Keys<span style="float:right"> 9  </span></li>
    <li> Executing a Query<span style="float:right"> 9  </span></li>
    <li> Introduction to JSON<span style="float:right"> 9  </span></li>
    <li> Working with JSON in R<span style="float:right"> 9  </span></li>
    <li> What is an API?<span style="float:right"> 9  </span></li>
</ol>

*** =right

<b class="toc_header"> III. Dealing with Missing Data </b>
<ol class = "toc" type="none">
    <li> Specialness of NAs<span style="float:right"> 14 </span></li>
    <li> You Should Care About NAs<span style="float:right"> 9  </span></li>
    <li> Strategy 1: Total Eradication<span style="float:right"> 9  </span></li>
    <li> Strategy 2: Handle At Application Level<span style="float:right"> 9  </span></li>
    <li> Strategy 3: Imputation<span style="float:right"> 9  </span></li>
</ol>

<b class="toc_header"> IV. Visualizing Data </b>
<ol class = "toc" type="none">
    <li> Graphics Devices<span style="float:right"> 15    </span></li>
    <li> Base Plotting System<span style="float:right"> 16-21</span></li>
    <li> ggplot2<span style="float:right"> 22-27</span></li>
    <li> rCharts<span style="float:right"> 28-30</span></li>
    <li> rbokeh<span style="float:right"> 31-32</span></li>
</ol>

--- .toc_slide &twocol

<footer>
  <hr></hr>
  <span style="float:right"> ECON 6931 - R Programming </span>
</footer>

<h2>Contents</h2>

*** =left

<b class="toc_header"> V. The apply() Family of Functions </b>
<ol class = "toc" type="none">
    <li> apply() <span style="float:right"> 29-30 </span></li>
    <li> lapply() <span style="float:right"> 31</span></li>
    <li> sapply() <span style="float:right"> 32-34</span></li>
    <li> apply Functions with UDFs <span style="float:right"> 35-36</span></li>
</ol>

<b class="toc_header"> VI. More data.table </b>
<ol class = "toc" type="none">
    <li> Applying functions over many columns<span style="float:right"> 29-30 </span></li>
    <li> data.table joins <span style="float:right"> 28-29 </span></li>
    <li> Fast rbind-ing of data.table objects <span style="float:right"> 28-29</span></li>
    <li> rbind-ing Heterogeneous Tables <span style="float:right"> 28-29</span></li>
</ol>

*** =right

<b class="toc_header"> VII. Final Project Discussion </b>
<ol class = "toc" type="none">
    <li> Project Proposal Guidelines <span style="float:right"> 29-30 </span></li>
    <li> Final Project Outline <span style="float:right"> 29-30 </span></li>
</ol>

--- .section_slide

<h2>Section I.</h2>
<hr></hr>
</br></br></br>
<h2>Getting Data from Databases</h2>

--- .section_slide

<h2>Section II.</h2>
<hr></hr>
</br></br></br>
<h2>Working With Web APIs</h2>

--- .section_slide

<h2>Section III.</h2>
<hr></hr>
</br></br></br>
<h2>Dealing With Missing Data</h2>

--- .section_slide

<h2>Section IV.</h2>
<hr></hr>
</br></br></br>
<h2>Visualizing Data</h2>

--- .section_slide

<h2>Section V.</h2>
<hr></hr>
</br></br></br>
<h2>The apply() Family of Functions</h2>

--- .section_slide

<h2>Section VI.</h2>
<hr></hr>
</br></br></br>
<h2>More data.table</h2>

--- .section_slide

<h2>Section VII.</h2>
<hr></hr>
</br></br></br>
<h2>Final Project Discussion</h2>

--- .content_slide

<footer>
  <hr>
    <script>FooterBubbles(1,7)</script>I. Introduction<span style="float:right">ECON 6931 - R Programming</span>
</footer>

<h2>Personal Introduction</h2>

