---
title       : ECON 6931 - R Programming
subtitle    : Week 4
author      : James Lamb
job         : Data Scientist | Uptake
logo        : 
framework   : io2012  # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [bootstrap]            # {mathjax, quiz}
mode        : selfcontained # {selfcontained, standalone, draft}
lib_cdn     : "https://cdn.rawgit.com/ramnathv/slidifyLibraries/master/inst/libraries"
knit        : slidify::knit2slides
--- .toc_slide &twocol

<script src="assets/js/footer_bubbles.js"></script>

<footer>
  <hr></hr>
  <span style="float:right">ECON 6931 - R Programming</span>
</footer>

<h2>Contents</h2>

*** =left

<b class="toc_header"> I. Introduction to Regular Expressions </b>
<ol class="toc" type="none">
    <li> Matching Simple Phrases <span style="float:right"> 5 </span></li>
    <li> Matching Character Sets<span style="float:right"> 5 </span></li>
    <li> Extracting Sub-Strings From a Match <span style="float:right"> 5 </span></li>
    <li> grep() vs. grepl() <span style="float:right"> 5 </span></li>
    <li> Regex + stringr <span style="float:right"> 5-7 </span></li>
</ol>

<b class="toc_header"> II. Dates and Time Series </b>
<ol class = "toc" type="none">
    <li> Default Date Class<span style="float:right"> 9  </span></li>
    <li> Using POSIX <span style="float:right"> 5 </span></li>
    <li> Navigating Time Zones <span style="float:right"> 5 </span></li>
    <li> Using lubridate to Clean Dates <span style="float:right"> 5 </span></li>
    <li> Regular Time Series: zoo <span style="float:right"> 5-8 </span></li>
    <li> Ordered but Irregular Time Series: xts <span style="float:right"> 5-8 </span></li>
</ol>

*** =right

<b class="toc_header"> III. Review of Material from Weeks 1-3 </b>
<ol class = "toc" type="none">
    <li> Subsetting <span style="float:right"> 14 </span></li>
    <li> Handling Missing Data <span style="float:right"> 14 </span></li>
    <li> Fitting and Predicting with Regression <span style="float:right"> 15-17 </span></li>
    <li> apply() Functions <span style="float:right"> 14-15 </span></li>
    <li>  <span style="float:right"> 14 </span></li>
</ol>

<b class="toc_header"> IV. Final Project Discussion </b>
<ol class = "toc" type="none">
    <li> Code Review Tips <span style="float:right"> 15    </span></li>
    <li> Scripting: Style Notes <span style="float:right"> 16-18 </span></li>
    <li> Report Guidelines <span style="float:right"> 15    </span></li>
</ol>

--- .section_slide

<h2>Section I.</h2>
<hr></hr>
</br></br></br>
<h2>Introduction to Regular Expressions</h2>

--- .section_slide

<h2>Section II.</h2>
<hr></hr>
</br></br></br>
<h2>Dates and Time Series</h2>

--- .section_slide

<h2>Section III.</h2>
<hr></hr>
</br></br></br>
<h2>Review of Material from Weeks 1-3</h2>

--- .section_slide

<h2>Section IV.</h2>
<hr></hr>
</br></br></br>
<h2>Discussion of Project Proposals</h2>

--- .content_slide

<footer>
  <hr>
    <script>FooterBubbles(1,7)</script>I. Introduction<span style="float:right">ECON 6931 - R Programming</span>
</footer>

<h2>Personal Introduction</h2>

