---
output: pdf_document
linkcolor: blue
urlcolor: blue
---

\textbf{ECON 6114} \hspace{30mm}
\textbf{R Programming} \hspace{30mm}
\textbf{Spring 2020}

\hrulefill

\textbf{Instructor:} James Lamb - jaylamb20@gmail.com | [Twitter](https://twitter.com/_jameslamb) | [LinkedIn](https://www.linkedin.com/in/jameslamb1) | [GitHub](https://github.com/jameslamb)

\hrulefill

\section{I. Course Info}

Welcome to R Programming!

\subsection{A. Learning Objectives and Outcomes}

In this course, we'll explore the basic building blocks of statistical programming in R. The course focuses on three parallel learning objectives: setting up an open-source software environment for practicing data science, translation of ideas to software solutions using R, and management and sharing of code. There will of course be some time spent learning syntax (e.g. "this is the command to do this thing in R"), but you'll also get the opportunity to hit each of these learning objectives through quizzes, programming assignments, a flexibly-defined final project and (finally) a "code review" presentation of your work.

The R ecosystem is huge and there are new features being added daily. You will not learn all or even most of what the language has to offer in this course, but you will leave with enough knowledge to hack together solutions to data-rich problems in your academic and professional lives.

\subsection{B. Course Resources and Communication}

**Your Professor:**

My contact information is given at the top of this syllabus. Email is my preferred contact method, and I will do my best to respond to all emails within 48 hours.

**Office Hours:**

I will be on campus at least an hour before class on the days we meet, and will host "office hours" in the classroom. I will clarify office hour details during our first session.

**Course Repo:**

All course resources (including this syllabus!) can be found at https://github.com/jameslamb/teaching/tree/main/mu_rprog.

BOOKMARK THIS RIGHT NOW: https://jameslamb.github.io/teaching/mu_rprog/

**Required Textbooks:**

None :)

**Required Hardware:**

\textcolor{red}{You are required to bring your own laptop to class.} If you do not have a personal laptop, please tell me as soon as possible and we can make other arrangements.

The use of personal hardware is required because one of the objectives for this course is to help each of you set up a data science friendly environment on your own machines.

**Required Software:**

We will be working with the [R programming language](https://www.r-project.org/). For script editing and exploratory analysis, we'll use [RStudio](https://www.rstudio.com/), a popular integrated development environment (IDE) for R.

Instructions for setting up all of these components can be found in the section below. Download and installation instructions are given in this syllabus, but we will also spend some time on the first day of class ensuring that everyone is set up.

**Slides and Assignment Rubrics:**

Slides and assignment rubrics will be available both in the "Content" section of the course page on D2L and on the course [GitHub repository](https://github.com/jameslamb/teaching/tree/main/mu_rprog).

\subsection{C. To-Do Before the First Session}

The course begins on 1/18/2020. Before class on that date, please do the following:

**1. Take the pre-course survey on [d2l](https://d2l.mu.edu/)**

The survey must be completed before the first day of class. This is just to help me understand your previous experience with programming and data science.

**2. Try to set up your development environment**

I'll devote some time in the first class to ensuring everyone is set up and resolving any lingering issues, so don't stress if you can't figure these out. I'm including the links here just to give you a chance to get a head start.

- Try to [install R v4.0.2](https://cloud.r-project.org/) or higher on your personal laptop
- Try to [install RStudio v1.3](https://www.rstudio.com/products/rstudio/download/) or higher on your personal laptop

I hope you'll be able to install these components using the information at those links and some moderate Googling. If you run into any issues, please email me and I'll help you out.

\subsection{D. Course Outline}

The outline below describes my goals for each lecture. Assignment due dates and lecture dates are fixed but content may change as the class progresses.

\underline{Week 1: January 18, 2020}

Due before class: Pre-course survey

\begin{itemize}
    \item Introductions
    \item Brief syllabus review
    \item Environment setup
    \item What is R?
    \item Variables, namespaces, objects, and types
    \item What is functional programming?
    \item Basic math operations in R
    \item Controlling program flow: if-then, for, and while
    \item Introduction to data frames
\end{itemize}

\underline{Week 2: January 25, 2020}

Due before class: Quiz 1

\begin{itemize}
    \item Using External Packages
    \item Fitting Regressions in R
    \item Subsetting
    \item Working with Files
    \item Introduction to data.table
    \item User-Defined Functions
    \item Debugging Strategies
\end{itemize}

\underline{Week 3: February 1, 2020}

Due before class: Quiz 2, Programming Assignment 1

\begin{itemize}
    \item Getting data from databases
    \item Working with web APIs
    \item Dealing with missing data
    \item Visualizing Data
    \item More data.table
    \item Final Project Discussion
\end{itemize}

\underline{Week 4: February 8, 2020}

Due before class: Programming Assignment 2, Final Project Proposal

\begin{itemize}
    \item Introduction to regular expressions
    \item Dates and Time Series
    \item Review of Material From Weeks 1-3
    \item Discussion of Project Proposals
\end{itemize}

\underline{Week 5: February 15, 2020}

Due before class: Final Project script + report

In class: Final Project code reviews

\begin{itemize}
    \item Final Project Code Reviews
    \item Intermediate R: functional programming
    \item Intermediate R: wrapping your code in a package
    \item R/Data Science AMA
\end{itemize}

\pagebreak

\section{II. Grading and Assignments}

You will receive a letter grade for this course. Grades will be assigned using the following scheme (also available under the "Grades" section of the course D2L page).

|Grade Item                      |Proportion of Final Grade |
|:------------------------------:|:------------------------:|
|Pre-Class Quiz                  |5\%                       |
|Quiz 1                          |10\%                      |
|Quiz 2                          |10\%                      |
|Programming Assignment 1        |15\%                      |
|Programming Assignment 2        |15\%                      |
|Final Project - Proposal        |10\%                      |
|Final Project - R script        |20\%                      |
|Final Project - Code Review     |10\%                      |
|Final Project - Written Report  |5\%                       |

And letter grades will be assigned using the following scale:

> \textbf{A}  - 92\% or higher \newline
> \textbf{A-} - 87\% $\leq$ grade < 92\% \newline
> \textbf{B+}  - 85\% $\leq$ grade < 87\% \newline
> \textbf{B}  - 82\% $\leq$ grade < 85\% \newline
> \textbf{B-} - 75\% $\leq$ grade < 82\% \newline
> \textbf{C+}  - 73\% $\leq$ grade < 75\% \newline
> \textbf{C}  - 70\% $\leq$ grade < 73\% \newline
> \textbf{F}  - Less than 70\%

The descriptions of all assignments are available immediately.

\subsection{A. Quizzes (25\%)}

There will be two quizzes which will test your understanding of topics covered in class. These quizzes will test your knowledge of terminology and core concepts. In addition, quizzes may require you to interpret pseudo-code or to write a bit of R code yourself to solve questions.

Quizzes will be delivered online via D2L (see the "Quizzes" section of the course site) and you are expected to complete them outside of class. Quizzes have no time limit. You will be allowed two attempts for each quiz and your grade on each quiz will be the better of your two scores.

|Quiz                       |Opens                             |Due                                 |
|:-------------------------:|:--------------------------------:|:----------------------------------:|
|Pre-class survey           | Immediately                      | Prior to Week 1 class (January 18) |
|Quiz 1                     | After Week 1 class (January 18)  | Prior to Week 2 class (January 25) |
|Quiz 2                     | After Week 2 class (January 25)  | Prior to Week 3 class (February 1) |

\subsection{B. Programming Assignments (30\%)}

After we've covered preliminary topics in the first two weeks of the course, I'll ask you to complete two programming assignments. In these assignments, you'll create R scripts to accomplish common tasks in data exploration and statistical analysis. 

Assignment rubrics can be found under the "Programming Assignments" module in the "Content" section of the course D2L page.

Your completed assignment must be uploaded to the appropriate folder in the "Dropbox" section on the course D2L page by the due date listed in the table below.

|Assignment                 |Due                                 |
|:-------------------------:|:----------------------------------:|
|Programming Assignment 1   | Prior to Week 3 class (February 1) |
|Programming Assignment 2   | Prior to Week 4 class (February 8) |

\subsection{C. Final Project (45\%)}

Unlike the quizzes and programming assignments, the final project will be relatively unstructured. In this project, you will be asked to augment what you've learned about base R with other functionality available in external packages. You will be responsible for building an end-to-end analysis in R...a script that gets/cleans real world data, creates some exploratory plots, executes some statistical analysis, and stores the results to a file for later re-use.

The project comprises four parts:

\begin{enumerate}
    \item \emph{Final project proposal}: A 1-2 page briefing on your planned project
    \item \emph{Final project script}: The R script/scripts supporting your project
    \item \emph{Final project report}: A 2-4 page report detailing the outcome of your analysis
    \item \emph{Final project code review}: You will give a 3-5 minute review of your project and code on the final day of class.
\end{enumerate}

Full details of the project and each of its components are available in the "Final Project" module in the "Content" section of the course D2L page.

|Assignment                      |Due                                  |
|:------------------------------:|:-----------------------------------:|
|Final Project proposal          | Prior to Week 4 class (February 8)  |
|Final Project (script + report) | Prior to Week 5 class (February 15) |
|Final Project code review       | In class Week 5 (February 15)       |

\subsection{D. Grade Appeal}

The grading policies described above will be used to calculate your final grade for the course. Individual assignment grades will follow rubrics available on the D2L site for this course. If you disagree with any grade assigned to you in this course, please frame all appeals in the language of this document + those rubrics.

\section{III. Administrative Information}

\subsection{A. Special Needs}

Please inform me during the first week of class if you have any conditions that may limit or affect your ability to participate in this course so that we can make necessary arrangements.  You may also contact the Office of Student Disability Services (OSES), in Marquette Hall 005 (8-1645) for more information (see also: http://www.marquette.edu/disability-services/).

\subsection{B. Emergency Plan}

Every Marquette University campus building has emergency shelter and evacuation plans. Please familiarize yourself with the plans of each building in which you take classes or attend meetings. Make sure to note the routes to the lowest level of the buildings for shelter during inclement weather, as well as exits from the buildings in the event of fire or other emergency.

\subsection{C. Attendance Statement}

The Marquette University Graduate School of Management considers regular class attendance an important component of the learning process. Students are expected to attend scheduled class meetings; excessive absences may have adverse consequences, ranging from a lowered course grade to forced withdrawal from the course. Excessive absence is generally defined as missing more than 10-15 percent of the regularly scheduled class time. Please consult \textbf{\emph{the instructor's course syllabus for additional details regarding a particular course}}.

For this course, anything more than 1 class period is determined to be "excessive". Because this is a short (5-week) course, missing even one week will make it difficult to learn the material and satisfactorily complete the course requirements. If you miss more than one class, your grade will be reduced by a full letter grade for each absence after the first. All students are expected to complete all quizzes, assignments, and the final project.

The policy above applies to "unexcused" absences. There are a handful of situations which are considered "excused" absences:

\begin{itemize}
    \item absences resulting from legal obligations (such as jury duty)
    \item absences resulting from university-sanctioned activities and related travel
    \item absences resulting from religious observance
\end{itemize}

If you anticipate missing any classes (even for the "excused" reasons mentioned above), please let me know as early as possible so we can plan accordingly.

\subsection{D. College of Business Administration Assessment Statement}

The fundamental mission of the College of Business Administration is to provide a quality education grounded in Catholic, Jesuit intellectual values.  Students are expected to learn how to function effectively in a diverse and global economy and develop into responsible members of the business community.  As one of many methods of assuring that the goals of our educational mission are successfully met, the college regularly and systematically engages in the assessment of these competencies.

Students in the Bachelor of Science in Business Administration program are assessed on their ability to reason ethically, communicate effectively, analyze critically, and understand local, national and global business and cultural issues.   Students in our MBA programs are also assessed on their competency to communicate effectively, reason ethically and apply critical thinking, as well as their capacity to comprehend the global strategic issues of firms and perform fundamental activities of business managers.  Students in our other graduate programs are assessed on specific competencies related to their disciplines.

Assessment takes place each semester in all programs and settings using quantifiable measures to gather and analyze information to help continuously improve the educational process.  The College of Business Administration is dedicated to successfully providing a quality education for all students.  Assessment is the continuous improvement process of evaluating our success.  More information on assessment can be found at http://www.marquette.edu/assessment/ or in the assurance of learning tabs under http://business.marquette.edu/academics/assurance-of-learning-undergrad or http://business.marquette.edu/academics/assurance-of-learning-graduate.

\subsection{E. Academic Integrity}

Don't cheat. For more see http://www.marquette.edu/provost/integrity-pledge.php.

**DEFINITIONS OF ACADEMIC DISHONESTY**

Academic dishonesty applies equally to electronic media and print and involves text, images and ideas. It includes but is not limited to the following examples:

\begin{itemize}
    \item \textbf{Cheating}
    \begin{itemize}
        \item Copying from others during an examination.
        \item Communicating exam answers with other students during an examination.
        \item Offering another person's work as one's own.
        \item Taking an examination for another student or having someone take an examination for oneself.
        \item Sharing answers for a take-home exam or assignment unless specifically authorized by the instructor.
        \item Tampering with an examination after it has been corrected and then returning it for more credit.
        \item Using unauthorized materials during an examination.
        \item Allowing others to do the research and writing of an assigned paper (including use of the services of a commercial term-paper company).
    \end{itemize}
    \item \textbf{Dishonest Conduct}
    \begin{itemize}
        \item Stealing or attempting to steal an examination or answer key from the instructor.
        \item Changing or attempting to change academic records without proper sanction.
        \item Submitting substantial portions of the same work for credit in more than one course without consulting all instructors involved.
        \item Intentionally disrupting the educational process in any manner.
        \item Allowing another student to copy off of one's own work during a test.
    \end{itemize}
    \item \textbf{Plagiarism}
    \begin{itemize}
        \item Stealing or passing off as one's own the ideas or words, images or other creative works of another
        \item Using a creative production without crediting the source, even if only minimal information is available to identify it for citation. Credit must be given for every direct quotation, for paraphrasing or summarizing a work (in whole, in part, in one's own words) and for information that is not common knowledge.
    \end{itemize}
    \item \textbf{Collusion}
    \begin{itemize}
        \item Knowingly or intentionally helping another student perform any of the above acts of cheating, dishonest conduct or plagiarism.
    \end{itemize}
\end{itemize}
